// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFsC5Nht1L13YuLBH_auOFXHBTzY14ct4',
    appId: '1:710152037421:web:71fb7feb74a0f6be2084a4',
    messagingSenderId: '710152037421',
    projectId: 'apartme-8cdc6',
    authDomain: 'apartme-8cdc6.firebaseapp.com',
    storageBucket: 'apartme-8cdc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKNwOJlrcalPwZu9LJDlhb_BU5wqkqFY',
    appId: '1:710152037421:android:0d7ecc763b7c0e522084a4',
    messagingSenderId: '710152037421',
    projectId: 'apartme-8cdc6',
    storageBucket: 'apartme-8cdc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcsuHuBMt5VVV4LJsmZSdvjxpurTE9knc',
    appId: '1:710152037421:ios:e781cff455d7b5dd2084a4',
    messagingSenderId: '710152037421',
    projectId: 'apartme-8cdc6',
    storageBucket: 'apartme-8cdc6.firebasestorage.app',
    iosBundleId: 'com.hebaarafat.apartme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcsuHuBMt5VVV4LJsmZSdvjxpurTE9knc',
    appId: '1:710152037421:ios:e781cff455d7b5dd2084a4',
    messagingSenderId: '710152037421',
    projectId: 'apartme-8cdc6',
    storageBucket: 'apartme-8cdc6.firebasestorage.app',
    iosBundleId: 'com.hebaarafat.apartme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFsC5Nht1L13YuLBH_auOFXHBTzY14ct4',
    appId: '1:710152037421:web:0523aa291e3360752084a4',
    messagingSenderId: '710152037421',
    projectId: 'apartme-8cdc6',
    authDomain: 'apartme-8cdc6.firebaseapp.com',
    storageBucket: 'apartme-8cdc6.firebasestorage.app',
  );

}